=== janvitu/XML_TeaProject/TeaSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:x-vitj07:schemas:tea:1.0" xmlns="urn:x-vitj07:schemas:tea:1.0" elementFormDefault="qualified">

    <xs:element name="caje" type="cajeType" />

    <xs:complexType name="cajeType">
        <xs:sequence>
            <xs:element name="caj" type="cajType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cajType">
        <xs:sequence>
            <xs:element name="typ" type="typType" />
            <xs:element name="druh" type="druhType" />
            <xs:element name="puvod" type="puvodType" />
            <xs:element name="pestovani" type="pestovaniType" minOccurs="0" />
            <xs:element name="vyroba" type="vyrobaType" minOccurs="0" />
            <xs:element name="priprava" type="pripravaType" />
            <xs:element name="popis" type="popisType" />
        </xs:sequence>
        <xs:attribute name="nazev" type="xs:string" />
        <xs:attribute name="ceskyNazev" type="xs:string" />
        <xs:attribute name="nazevIMG" type="nazevIMGType" />
    </xs:complexType>

    
    <xs:simpleType name="nazevIMGType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\.png" />
        </xs:restriction>
    </xs:simpleType>
    <!-- typ caje -->
    <xs:simpleType name="typType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="matcha" />
            <xs:enumeration value="celolisty" />
            <xs:enumeration value="sekany" />
        </xs:restriction>
    </xs:simpleType>

    <!-- druh caje -->
    <xs:simpleType name="druhType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Oolong" />
            <xs:enumeration value="PuErh" />
            <xs:enumeration value="Černý čaj" />
            <xs:enumeration value="Bílý čaj" />
            <xs:enumeration value="Zelený čaj" />
            <xs:enumeration value="Žlutý čaj" />
            <xs:enumeration value="Červený čaj" />
        </xs:restriction>
    </xs:simpleType>

    <!-- puvod caje -->
    <xs:complexType name="puvodType">
        <xs:sequence>
            <xs:element name="zeme" type="xs:string" />
            <xs:element name="oblast" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <!-- pestovani -->
    <xs:complexType name="pestovaniType">
        <xs:sequence>
            <xs:element name="nadmorskaVyska" type="xs:positiveInteger" minOccurs="0" />
            <xs:element name="strom" type="stromType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stromType">
        <xs:sequence>
            <xs:element name="druhStromu" type="druhStromuType" minOccurs="0" />
            <xs:element name="vek" type="xs:positiveInteger" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="druhStromuType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="divoky" />
            <xs:enumeration value="pestovany" />
        </xs:restriction>
    </xs:simpleType>

    <!-- vyroba -->
    <xs:complexType name="vyrobaType">
        <xs:sequence>
            <xs:element name="sklizen" type="sklizenType" />
            <xs:element name="fermentace" type="fermentaceType" minOccurs="0" />
            <xs:element name="oxidace" type="oxidaceType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="sklizenType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1. sklizen" />
            <xs:enumeration value="2. sklizen" />
            <xs:enumeration value="3. sklizen" />
            <xs:enumeration value="4. sklizen" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fermentaceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nefermentovany" />
            <xs:enumeration value="castecne fermentovany" />
            <xs:enumeration value="plne fermentovany" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="oxidaceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="neoxidovany" />
            <xs:enumeration value="castecne oxidovany" />
            <xs:enumeration value="plne oxidovany" />
        </xs:restriction>
    </xs:simpleType>

    <!-- priprava -->
    <xs:complexType name="pripravaType">
        <xs:sequence>
            <xs:element name="mnozstvi" type="mnozstviListyType" />
            <xs:element name="voda" type="vodaType" />
            <xs:element name="cas" type="casType" />
            <xs:element name="druhNadobi" type="druhNadobyType" />
        </xs:sequence>
    </xs:complexType>
    <!-- priprava mnozstvi listu -->
    <xs:complexType name="mnozstviListyType">
        <xs:simpleContent>
            <xs:extension base="mnozstviListyRestrictionType">
                <xs:attribute name="jednotky" type="jednotkyMnozstviListType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="mnozstviListyRestrictionType">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="jednotkyMnozstviListType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="g" />
            <xs:enumeration value="mg" />
        </xs:restriction>
    </xs:simpleType>

    <!-- priprava voda -->
    <xs:complexType name="vodaType">
        <xs:sequence>
            <xs:element name="mnozstvi" type="mnozstviVodaType" />
            <xs:element name="teplota" type="teplotaType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mnozstviVodaType">
        <xs:simpleContent>
            <xs:extension base="mnozstviVodaExtensionType">
                <xs:attribute name="jednotky" type="jednotkyMnozstviVodaType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="mnozstviVodaExtensionType">
        <xs:restriction base="xs:positiveInteger"></xs:restriction>
    </xs:simpleType>

    <xs:complexType name="teplotaType">
        <xs:simpleContent>
            <xs:extension base="teplotaExtensionType">
                <xs:attribute name="jednotky" type="jednotkyTeplotaType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="teplotaExtensionType">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="jednotkyMnozstviVodaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ml" />
            <xs:enumeration value="dcl" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="jednotkyTeplotaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="°C" />
            <xs:enumeration value="°F" />
        </xs:restriction>
    </xs:simpleType>

    <!-- priprava cas -->
    <xs:complexType name="casType">
        <xs:sequence>
            <xs:element name="nalev" type="nalevType" minOccurs="1" maxOccurs="4" >
                <xs:unique name="nalev">
                    <xs:selector xpath="caje/caj/priprava/cas/nalev"></xs:selector>
                    <xs:field xpath="caje/caj/priprava/cas/nalev/@poradi"></xs:field>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="jednotky" type="jednotkyBrewTimeType"></xs:attribute>
    </xs:complexType>
       
    
    <xs:complexType name="nalevType">
        <xs:simpleContent>
            <xs:extension base="nalevExtensionType">
                <xs:attribute name="poradi" type="poradiInterval" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="nalevExtensionType">
        <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>

    <xs:simpleType name="poradiInterval">
        <xs:restriction base="xs:positiveInteger">
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
            <xs:enumeration value="3" />
            <xs:enumeration value="4" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="jednotkyBrewTimeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="s" />
            <xs:enumeration value="min" />
        </xs:restriction>
    </xs:simpleType>

    <!-- priprava druh nadobi -->
    <xs:complexType name="druhNadobyType">
        <xs:sequence>
            <xs:element name="material" type="materialType" />
            <xs:element name="kalisek" type="kalisekType" minOccurs="0" maxOccurs="1" />
            <xs:element name="konvicka" type="konvickaType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="materialType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Tokoname" />
            <xs:enumeration value="Bizen" />
            <xs:enumeration value="Porcelan" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="kalisekType">
        <xs:sequence>
            <xs:element name="prumer" type="rozmeryType" />
            <xs:element name="hloubka" type="rozmeryType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rozmeryType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="jednotky" type="rozmeryJednotkyType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="rozmeryJednotkyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="cm" />
            <xs:enumeration value="mm" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="objemType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="jednotky" type="jednotkyMnozstviVodaType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="konvickaType">
        <xs:sequence>
            <xs:element name="objem" type="objemType" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="popisType">
        <xs:restriction base="xs:string">
            <xs:minLength value="0" />
            <xs:maxLength value="255" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== janvitu/XML_TeaProject/TeaDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<caje xmlns="urn:x-vitj:schemas:tea:1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:x-vitj:schemas:tea:1.0 TeaSchema.xsd">
    <caj nazev="" ceskyNazev=""> <!-- Čaj může a nemusí obsahovat český název -->
        <typ>matcha</typ> <!-- hodnotou je matcha, sekaný list nebo celolistý -->
        <druh>PuErh</druh> <!-- druhů čajů je několik Olong, PuErh, Černý čaj, Bílý čaj, Zelený čaj, Žlutý čaj, Červený čaj -->
        <puvod> <!-- diky původu lze snadno určit připravu čaje, čínské čaje jsou více fermentované a velice výrazné vúní, japonské čaje jsou výrazné svojí chutí, díky tomuto se i rozličuje způsob připravy a servírování -->
            <zeme></zeme>
            <oblast></oblast>
        </puvod>
        <pestovani>
            <nadmorskaVyska>200</nadmorskaVyska> <!-- nadmořská výška určuje velikost lístků a potřebu množství lístů -->
            <strom> <!-- v podstatě není čajovník jako čajovník je potřeba rozlyšovat jeho věk, mladé stromy jsou vhodné pro světlé čaje, staré stromy jsou určeny pro tmavé čaje -->
                <druhStromu>divoky</druhStromu> <!-- strom může být divoký nebo člověkem vypěstovaný, divoké čajovníky mají tu vlastnost že v jejich listech je mnoho chutí a tyto chutě nejsou konstantní jako u pěstovaných čajovníků člověkem -->
                <vek>1000</vek>
                <korenovePropojeni> <!-- samotný strom může "získat sílu" za využití propojení kořenových systémů a tím částečně získat vlastnosti staršího stromu -->
                    <pripojenyStrom>
                        <vek>1000</vek>
                    </pripojenyStrom>
                </korenovePropojeni>
            </strom>
        </pestovani>
        <vyroba>
            <sklizen>1. sklizen</sklizen> <!-- některé druhy čajů jsou zbírané ve více sezónách tzv. flush (1st flush jaro – je velice jemný a spíše vhodný pro světlé čaje) 2nd a 3rd flush (léto) je vhodný pro červené čaje, 4th flush je vhodný pro tmavé čaje s velice surovou chutí  -->
            <fermentace>nefermentovany</fermentace>
            <oxidace>neoxidovany</oxidace>
        </vyroba>
        <priprava>
            <mnozstvi jednotky="g">5</mnozstvi> <!-- množství je důležité pro plnost chuti čaje, pokud je dáno málo je čaj jemnější, pokud více je velice surový a chuť obsahuje úplnou strukturu -->
            <voda> <!-- není důležitá pouze kvalita vody, ale její teplota a množství pokud použijeme malé množství vody pro velké množství čaje, tak čaj nedokáže vypustit požadované látky -->
                <mnozstvi jednotky="ml">250</mnozstvi>
                <teplota jednotky="°C">90</teplota> <!-- teplota ovlivňuje trpkost a chuť čaje, zelené čaje jsou velice čerstvé lístky, které při kontaktu se 100ºC vodou ztrpkne, zhořkne a je takřka nepoživatelný -->
            </voda>
            <cas jednotky="s"> <!-- čas má podobné účinky jako teplota avšak při správné teplotě mnoho čajů vydrží velice dlouhé nálevy -->
                <prvniNalev>30</prvniNalev> <!-- u některých čajů je potřeba měnit čas nálevu podle pořadí nálevu, některé čaje se více rozevřou(lístky) a nabydou na objemu, díky tomu dokaží předat více látek během kratší doby -->
                <druhyNalev>15</druhyNalev>
                <tretiNalev>10</tretiNalev>
                <ostatniNalevy>10</ostatniNalevy>
            </cas> 
            <druhNadobi> <!-- druh nádobí ovlivňuje chuť čaje, čaj který je připravovaný v nevyhovujícím nádobí nikdy nebude chuťově plný -->
                <materiál></materiál> <!-- materiály se dělí podle jednotlivých provincií a oblastí, kde se vyrábějí například Tokoname nebo Bizen -->
                <kalisek druh=""> <!-- Druh kalíšku je určen hlavním druhem čaje – Matcha se připravuje v čavanech, ale běžný sekaný nebo lístkový čaj se připravuje v konvičce -->
                    <prumer jednotky="cm">10</prumer> <!-- je dlůležité rozlyšovat jednotlivé druhy čajů a využívat jejich potenciál například číské čaje vyžadují vetší kalíšky z důvodu vychutnání si vůně i chuti-->
                    <hloubka jednotky="cm">10</hloubka>
                    <objem jednotky="ml">200</objem>
                </kalisek>
                <konvicka>
                    <objem jednotky="ml">200</objem>
                </konvicka>
            </druhNadobi>
        </priprava>
        <popis>Something new</popis> <!-- popis slouží k popsání chuti čaje -->        
    </caj>
</caje>
